server:
  port: 8000
  compression:
    enabled: true
    mime-types: application/json

springdoc:
  swagger-ui:
    path: /doc.html
    tags-sorter: alpha
    operations-sorter: alpha
    show-extensions: true
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'backend-ai-template'
      paths-to-match: '/**'
      packages-to-scan: org.visage.backend.controller
  default-flat-param-object: false

spring:
  application:
    name: backend-ai-template
  ai:
    openai:
      api-key: sk-ddba484efb7f41dcac8ab681e43ac87f
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat

